/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.flaviodev.kfjd

import com.flaviodev.kfjd._01fromjavatokotlin.Color
import com.flaviodev.kfjd._01fromjavatokotlin.updateWeather
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class FromJavaToKotlinTest {
    @Test fun testUpdateWeatherWithDegreesLessThan10() {
        val classUnderTest = updateWeather(2)
        assertEquals(classUnderTest.first,"cold")
        assertEquals(classUnderTest.second,Color.BLUE)
    }

    @Test fun testUpdateWeatherWithDegreesEquals10() {
        val classUnderTest = updateWeather(10)
        assertEquals(classUnderTest.first,"warm")
        assertEquals(classUnderTest.second,Color.ORANGE)
    }

    @Test fun testUpdateWeatherWithDegreesLessThan25() {
        val classUnderTest = updateWeather(20)
        assertEquals(classUnderTest.first,"warm")
        assertEquals(classUnderTest.second,Color.ORANGE)
    }

    @Test fun testUpdateWeatherWithDegreesEquals25() {
        val classUnderTest = updateWeather(25)
        assertEquals(classUnderTest.first,"hot")
        assertEquals(classUnderTest.second,Color.RED)
    }

    @Test fun testUpdateWeatherWithDegreesGraterThan25() {
        val classUnderTest = updateWeather(45)
        assertEquals(classUnderTest.first,"hot")
        assertEquals(classUnderTest.second,Color.RED)
    }
}
